name: build-and-release-gentoo-wsl

on:
  schedule:
    # 每天 08:30 UTC ≈ 北京时间 16:30，可按需修改
    - cron: '30 8 * * *'
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/build-release.yml
      - build_gentoo_wsl.sh
      - oobe.sh
      - gentoo-signet-128x128.ico

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      API_URL: https://distfiles.gentoo.org/releases/amd64/autobuilds/current-stage3-amd64-openrc/latest-stage3-amd64-openrc.txt
    outputs:
      release_exists: ${{ steps.check_release.outputs.exists }}
      tag: ${{ steps.tag.outputs.tag }}
      latest: ${{ steps.latest.outputs.latest }}
    steps:
      - uses: actions/checkout@v4

      - id: latest
        run: |
          LATEST=$(curl -s $API_URL | grep stage3 | awk '{print $1}')
          echo "latest=$LATEST" >> $GITHUB_OUTPUT

      - id: tag
        run: |
          FILE="${{ steps.latest.outputs.latest }}"
          TAG=$(echo "$FILE" | grep -oE '[0-9]{8}')
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - id: check_release
        run: |
          if gh release view "${{ steps.tag.outputs.tag }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Release already exists."
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "No release yet. Will proceed."
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: check
    if: needs.check.outputs.release_exists == 'false'
    runs-on: ubuntu-latest
    env:
      TAG: ${{ needs.check.outputs.tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Install build deps
        run: sudo apt-get update && sudo apt-get install -y xz-utils jq

      - name: Build .wsl package
        run: |
          chmod +x build_gentoo_wsl.sh
          sudo ./build_gentoo_wsl.sh
          mv gentoo_*.wsl gentoo_${TAG}.wsl

      - name: Compute SHA
        id: hash
        run: |
          HASH=$(sha256sum gentoo_${TAG}.wsl | awk '{print $1}')
          echo "sha=$HASH" >> $GITHUB_OUTPUT

      - name: Write .sha256
        run: echo "${{ steps.hash.outputs.sha }}  gentoo_${TAG}.wsl" > gentoo_${TAG}.sha256

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: "Gentoo WSL (${{ env.TAG }})"
          body: |
            Automated build for stage3 **${{ env.TAG }}**

            **SHA-256**
            ```
            ${{ steps.hash.outputs.sha }}
            ```
            * Gentoo stage3-amd64-openrc snapshot  
            * Pre-installed sudo, OOBE user setup  
            * Built by GitHub Actions
          files: |
            gentoo_${{ env.TAG }}.wsl
            gentoo_${{ env.TAG }}.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
